config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :wishboards
  resources :lists
  get '/', to: 'application#home'
  get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: "sessions#new", as: "login"
post '/login', to: "sessions#create"
get '/logout', to: "sessions#destroy", as: "logout"
#get 'authorized', to: 'sessions#page_requires_login'
get '/auth/facebook/callback' => 'sessions#facebook' #changedfromcreate
#get '/delete', to: "posts#destroy", as: "delete"
resources :artists, only: [:show] do
 resources :posts, only: [:show, :index]
end

resources :users
resources :posts
resources :comments
resources :artists
resources :records
resources :genres
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories
    has_many :posts, through: :post_categories
    
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :post
    validates :message, presence: true, allow_blank: false
    accepts_nested_attributes_for :user, reject_if: proc { |attributes| attributes['username'].blank?}

  def user_attributes(user_attributes)
    user_attributes.values.each do |user_attributes|
      if user_attributes[:username].present?
        user = User.find_or_create_by(user_attributes)
        if !self.user = user
          self.build_user(:username => user[:username])
        end
      end
    end
  end

    def post_ids=(ids)
      ids.each do |id|
      post = Post.find(id)
        self.posts << post
      end
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :records
    has_many :artists
    has_many :post_genres
    has_many :posts, through: :post_genres
    has_many :posts
     def post_ids=(ids)
      ids.each do |id|
       post = Post.find(id)
      self.posts << post
       end
      end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_associated :user
  validates_associated :record
  validates_associated :genres
  validates_associated :artist
    belongs_to :user
    has_many :post_genres
    has_many :genres, through: :post_genres
    belongs_to :artist
    has_one :record
    has_many :comments
    has_many :users, through: :comments
    accepts_nested_attributes_for :record, :genres, :artist
    has_one_attached :image
    has_many :post_categories
    has_many :categories, through: :post_categories
    
    def self.by_artist(artist_id)
      where(artist: artist_id)
    end
    
      def user_ids=(ids)
       ids.each do |id|
       user = User.find(id)
         self.users << user
        end
     end
 
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
    belongs_to :category
    belongs_to :post
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/postsgenre.rb
class PostsGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :post, optional: true
    belongs_to :genre, optional: true
    belongs_to :artist, optional: true
end

app/models/user.rb
class User < ApplicationRecord
   # devise :omniauthable, :omniauth_providers => [:facebook]
    validates :username, :email, presence: true
    #validates :email, :username, uniqueness: true
   #validates :password, length: { in: 6..20 }
    validates :username, format: { without: /[0-9]/, message: "does not allow numbers" }
   # has_many :genres
    has_many :comments
    has_many :posts, through: :comments
    has_many :records
    has_many :posts
    has_many :lists
    accepts_nested_attributes_for :lists
   # has_many :user_posts
   # has_many :posts, through: :user_posts
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end 
    
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def show 
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
    end

app/helpers/application_helper.rb
module ApplicationHelper
   # module SessionsHelper







end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

    
end

app/helpers/records_helper.rb
module RecordsHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishboards_helper.rb
module WishboardsHelper
end

app/views/users/index.html.erb
<ul>
<% @users.each do |user| %>
<li> <%= link_to user.username, user_path(user.id) %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being saved:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<center>
<h2>Sign Up</h2>


<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <%= f.label :email %>
  <%= f.email_field :email %><br>
  <%= f.label :password %>
  <%= f.text_field :password %><br>
  <%= f.submit %>
<% end %>
</center>

app/views/users/show.html.erb
<h2><%= @user.username %> </h2> has commented on the following posts:<br>

Comments:
    <% @user.comments.each do |comment| %>
    <%= link_to comment.user.username, user_path(comment.user) %> said
    <%= comment.message %><br>
    <% end %>
      
    Posts:<br>
    <% @user.posts.each do |post| %>
    POST: <%= post.name %> <br>
    <% if post.image.attached? %>
    <%= image_tag post.image %><br>
    <% end %>
    Album Title:
    <%= post.record.title %><br>
    Genre:
    <% post.genres.each do |genre| %>
    <%= genre.name %><br>
    <% end %>
    <%= post.artist.name %><br>
    <% post.categories.each do |category| %>
    <%= category.name %>
    <% end %>
    Contents:
    <%= post.contents %><br>
    <%= link_to "Edit Post", edit_post_path(post) %><br>
    <%= button_to "delete", post, :method => :delete %><br>
    <%= link_to post.name, post_path(@user, post) %><br>
    <% end %>


<% if current_user %>
<%=     link_to "Logout", logout_path %>
<% else %>
<%=     link_to "Login", :controller => 'sessions', :action => 'new' %>


</center>
<% end %>