config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :wishboards
  resources :lists
  get '/', to: 'application#home'
  get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: "sessions#new", as: "login"
post '/login', to: "sessions#create"
get '/logout', to: "sessions#destroy", as: "logout"
#get 'authorized', to: 'sessions#page_requires_login'
get '/auth/facebook/callback' => 'sessions#facebook' #changedfromcreate
#get '/delete', to: "posts#destroy", as: "delete"
resources :artists, only: [:show] do
 resources :posts, only: [:show, :index]
end

resources :users
resources :posts
resources :comments
resources :artists
resources :records
resources :genres
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories
    has_many :posts, through: :post_categories
    
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :post
    validates :message, presence: true, allow_blank: false
    accepts_nested_attributes_for :user, reject_if: proc { |attributes| attributes['username'].blank?}

  def user_attributes(user_attributes)
    user_attributes.values.each do |user_attributes|
      if user_attributes[:username].present?
        user = User.find_or_create_by(user_attributes)
        if !self.user = user
          self.build_user(:username => user[:username])
        end
      end
    end
  end

    def post_ids=(ids)
      ids.each do |id|
      post = Post.find(id)
        self.posts << post
      end
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :records
    has_many :artists
    has_many :post_genres
    has_many :posts, through: :post_genres
    has_many :posts
     def post_ids=(ids)
      ids.each do |id|
       post = Post.find(id)
      self.posts << post
       end
      end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_associated :user
  validates_associated :record
  validates_associated :genres
  validates_associated :artist
    belongs_to :user
    has_many :post_genres
    has_many :genres, through: :post_genres
    belongs_to :artist
    has_one :record
    has_many :comments
    has_many :users, through: :comments
    accepts_nested_attributes_for :record, :genres, :artist
    has_one_attached :image
    has_many :post_categories
    has_many :categories, through: :post_categories
    
    def self.by_artist(artist_id)
      where(artist: artist_id)
    end
    
      def user_ids=(ids)
       ids.each do |id|
       user = User.find(id)
         self.users << user
        end
     end
 
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
    belongs_to :category
    belongs_to :post
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/postsgenre.rb
class PostsGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :post, optional: true
    belongs_to :genre, optional: true
    belongs_to :artist, optional: true
end

app/models/user.rb
class User < ApplicationRecord
   # devise :omniauthable, :omniauth_providers => [:facebook]
    validates :username, :email, presence: true
    #validates :email, :username, uniqueness: true
   #validates :password, length: { in: 6..20 }
    validates :username, format: { without: /[0-9]/, message: "does not allow numbers" }
   # has_many :genres
    has_many :comments
    has_many :posts, through: :comments
    has_many :records
    has_many :posts
    has_many :lists
    accepts_nested_attributes_for :lists
   # has_many :user_posts
   # has_many :posts, through: :user_posts
    has_secure_password
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
      def index
        @artists = Artist.all
        if !params[:artist].blank?
          @posts = Post.by_artist(params[:artist])
        else 
          @posts = Post.all
        end
      end

    def new
        @post = Post.new
        @post.user = current_user
        @record = @post.build_record(title: "title",
        id: :id)
        @artist = @post.build_artist(name: "name",
        id: :id)
        @genres = @post.genres.build([
        { name: "test", id: [] }])
    end
        
 
    def create
          @post = Post.create(post_params)
          @post.user = current_user
          @post.image.attach(params[:post][:image])
        if @post.save
           redirect_to post_path(@post)
        else 
            render :new 
        end
    end

    
    def edit
        @post = Post.find(params[:id])
    end

    def update
         @post = Post.find(params[:id])
      if @post.update(post_params)
         redirect_to @post
      else
        render 'edit'
      end
    end
        
    def show
        @post = Post.find(params[:id])
        binding.pry
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to users_path(@user)
    end 

    private
    
    def post_params
      params.require(:post).permit(:name, :contents, :image, :user_id, category_ids: [], genres_attributes: [:name, :id], artist_attributes: [:name, :id], record_attributes: [:title, :id])
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   # module SessionsHelper







end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

    
end

app/helpers/records_helper.rb
module RecordsHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishboards_helper.rb
module WishboardsHelper
end

app/views/posts/_form.html.erb
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "error") %>
          prohibited this post from being saved:
        </h2>
    
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        </ul>
      </div>
    <% end %>
  <% end %>
  
  

app/views/posts/edit.html.erb
<center>
<h1>Edit Post</h1>
<%= form_for(@post) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %><br>
        <%= f.label :contents %>
        <%= f.text_field :contents %><br>
        <%= f.hidden_field :user_id %>

        <%= f.fields_for :artist, @post.artist do |artist_attributes| %>
                <%= artist_attributes.label :artist_name %>
                <%= artist_attributes.text_field :name %><br>
       
        <%= f.fields_for :record do |record_attributes| %>
        <%= record_attributes.label :record_title %>
        <%= record_attributes.text_field :title %><br>

        <%= f.fields_for :genres, @post.genres do |genre_attributes| %>
                <%= genre_attributes.label :genre_name %>
           <%= genre_attributes.collection_select :name, Genre.all, :id, :name %><br>
        <% end %>

        <% end %>
        <%= f.label :image %>
        <%= f.file_field :image %><br>
        <%= f.submit %>
        <% end %>
</center><% end %>

app/views/posts/index.html.erb
<h3>Filter posts:</h3>
  <%= form_tag("/posts", method: "get") do %>
    <%= select_tag "artist", options_from_collection_for_select(@artists, "id", "name") %>
    <%= submit_tag "Filter" %>
  <% end %>

  <% @posts.each do |post| %>

  <strong> <h3><%= post.name %></h3> </strong><br>
  ALBUM:<p><%= post.record.title %></p>
  ARTIST:<p><%= post.artist.name %></p>
  <% post.genres.each do |genre| %>
    GENRE:<p><%= genre.name %></p>
    <% end %>
  <% if post.image.attached? %>
  <li><%= image_tag post.image %></li>
  <% end %>
  <% post.categories.each do |category| %><br>
    <%= category.name %><br>
    <% end %>
  <div><%= post.contents %></div>
  <% post.comments.each do |comment| %>
  COMMENT: <strong><%= comment.message %></strong> <br>
  <br>
  <em style="font-size:14px; color:black">
  posted by: <%= comment.user.username %>
  <% end %>
  <%= link_to "Add Comment", new_comment_path(post_id: post.id) %>
  <% end %>




  


  

app/views/posts/new.html.erb
<%= render "form" %>
<center>
<h1>Make A New Post</h1>
<%= form_for(@post) do |f| %>
        <%= f.label :post_name %>
        <%= f.text_field :name %><br>
        <%= f.label :contents %>
        <%= f.text_area :contents, size: "30x5" %><br>
        <%= f.label :image %>
        <%= f.file_field :image %>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %><br>
  
        <%= f.collection_select :genres, Genre.all, :id, :name %><br>
        <%= f.fields_for :record, @post.record do |record_attributes| %>
        <%= record_attributes.label :Record_Title %>
        <%= record_attributes.text_field :title %><br>
       
        <%= f.fields_for :artist, @post.artist do |artist_attributes| %>
          <%= artist_attributes.label :artist_name %>
          <%= artist_attributes.text_field :name %><br>
        <% end %>
        <%= f.submit %>
        <% end %>
        </center>
        <% end %>
   

app/views/posts/show.html.erb
<center>
<%= @post.user.username.pluralize.upcase %><br> new post
<div> <h3><%= @post.name %></h3><br></div>

album title:<br>
<%= @post.record.title %><br>
artist name:
<%= @post.artist.name %><br>
Genre:name
<% @post.genres.each do |genre| %><br>
<%= genre.name %><br>
<% end %>
<br><% if @post.image.attached? %>
<%= image_tag @post.image %><br>
<% @post.categories.each do |category| %><br>
<%= category.name %><br>
<% end %>
<br> Contents: <%= @post.contents %><br>
<%= link_to "Edit Post", edit_post_path(@post) %>
  
<%= button_to "Delete post", post_path(@post), method: :delete %>
</center>
<% end %>

Comments:
<% @post.comments.each do |comment| %>
<%= link_to comment.user.username, user_path(comment.user) %> said
<%= comment.content %> 
<% end %>
  