config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :wishboards
  resources :lists
  get '/', to: 'application#home'
  get '/signup', to: 'users#new'
post '/signup', to: 'users#create'
get '/login', to: "sessions#new", as: "login"
post '/login', to: "sessions#create"
get '/logout', to: "sessions#destroy", as: "logout"
#get 'authorized', to: 'sessions#page_requires_login'
get '/auth/facebook/callback' => 'sessions#facebook' #changedfromcreate
#get '/delete', to: "posts#destroy", as: "delete"
resources :artists, only: [:show] do
 resources :posts, only: [:show, :index]
end

resources :users
resources :posts
resources :comments
resources :artists
resources :records
resources :genres
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :posts
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :post_categories
    has_many :posts, through: :post_categories
    
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user 
    belongs_to :post
    validates :message, presence: true, allow_blank: false
    accepts_nested_attributes_for :user, reject_if: proc { |attributes| attributes['username'].blank?}

  def user_attributes(user_attributes)
    user_attributes.values.each do |user_attributes|
      if user_attributes[:username].present?
        user = User.find_or_create_by(user_attributes)
        if !self.user = user
          self.build_user(:username => user[:username])
        end
      end
    end
  end

    def post_ids=(ids)
      ids.each do |id|
      post = Post.find(id)
        self.posts << post
      end
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :records
    has_many :artists
    has_many :post_genres
    has_many :posts, through: :post_genres
    has_many :posts
     def post_ids=(ids)
      ids.each do |id|
       post = Post.find(id)
      self.posts << post
       end
      end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_associated :user
  validates_associated :record
  validates_associated :genres
  validates_associated :artist
    belongs_to :user
    has_many :post_genres
    has_many :genres, through: :post_genres
    belongs_to :artist
    has_one :record
    has_many :comments
    has_many :users, through: :comments
    accepts_nested_attributes_for :record, :genres, :artist
    has_one_attached :image
    has_many :post_categories
    has_many :categories, through: :post_categories
    
    def self.by_artist(artist_id)
      where(artist: artist_id)
    end
    
      def user_ids=(ids)
       ids.each do |id|
       user = User.find(id)
         self.users << user
        end
     end
 
end

app/models/post_category.rb
class PostCategory < ApplicationRecord
    belongs_to :category
    belongs_to :post
end

app/models/post_genre.rb
class PostGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/postsgenre.rb
class PostsGenre < ApplicationRecord
    belongs_to :post
    belongs_to :genre
end

app/models/record.rb
class Record < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :post, optional: true
    belongs_to :genre, optional: true
    belongs_to :artist, optional: true
end

app/models/user.rb
class User < ApplicationRecord
   # devise :omniauthable, :omniauth_providers => [:facebook]
    validates :username, :email, presence: true
    #validates :email, :username, uniqueness: true
   #validates :password, length: { in: 6..20 }
    validates :username, format: { without: /[0-9]/, message: "does not allow numbers" }
   # has_many :genres
    has_many :comments
    has_many :posts, through: :comments
    has_many :records
    has_many :posts
    has_many :lists
    accepts_nested_attributes_for :lists
   # has_many :user_posts
   # has_many :posts, through: :user_posts
    has_secure_password
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

    
end

app/helpers/records_helper.rb
module RecordsHelper
    
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishboards_helper.rb
module WishboardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
div {
  background-color: lightgrey;
  width: 300px;
  border: 20px solid gray;
  padding: 5px;
  margin: 20px;
  text-align: center
}
</style>

<style>
p {
  background-color: lightgrey;
  width: 100px;
  border: 5px solid pink;
  padding: 4px;
  margin: 20px;
  text-align: center
}
</style>
</head>
<body>

<div class="container">
      <p style="text-align:left;">
        <h1 style="font-family:'Courier New';" style="color:Black;"><strong>Vinyl Heads</strong></h1>
        <img src="https://cdn.shopify.com/s/files/1/0580/0965/products/hu8EvlLSLy6BI50kkLpQ_web_productimage_rezinfinite_vinyl_8.jpg" width="100" height="100">
      <h3 style="font-family:'Courier New';" style="color:Black;"><strong>The App for Music Lovers.</strong></h3>
      <h5 style="font-family:'Courier New';" style="color:Black;"><strong>start up a conversation</strong></h5>
      </p>
    </div>

   <div class="nav">
     <p style="text-align:center;" style="color:DarkBlue;">
     <% if current_user %>
     <%= link_to "Logout", logout_path %>
     <%= link_to "Userspage", user_path(current_user.id) %>
     <%= link_to "Browse Records", records_path %>
     <%= link_to "Make a Post", new_post_path %>
     <%= link_to "View all Records", posts_path %>
     <% else %>
     <%= link_to "Login", :controller => 'sessions', :action => 'new' %>
     <% end %>
     </p>
  </div>
    <title>Vinyl_Heads</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/style.css">
    <body style="background-color:Teal;">
    
  </head>
 
  <body>

    
<center>
    <%= yield %>

    <style>

   </center>

  </body>
 
</html>